title: Rakshitha BS
logo: /assets/img/logo.png
description: 
Software engineer seeking opportunities in machine learning. Skilled in Python, data analysis, and implementing machine learning models. Passionate about developing innovative solutions to complex problems using data-driven approaches. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
