title: Rakshitha BS
logo: /assets/img/IMG_20211226_072859__02__01__01.jpg
description: Software Engineer and a Machine Learning enthusiast passionate about building and productionizing scalable machine learning systems.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
