title: Rakshitha BS
logo: /assets/img/IMG_20211226_072859__02__01__01.jpg
description: Software engineer seeking opportunities in machine learning. Skilled in Python, data analysis, and implementing machine learning models. Passionate about developing innovative solutions to complex problems using data-driven approaches. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
